import { useEffect, useState } from "react";

import DataTable from "../components/DataTable";
import { getDisputes } from "../services/api";

function Disputes() {
  const [disputes, setDisputes] = useState([]);

  useEffect(() => {
    getDisputes()
      .then((response) => setDisputes(response.data))
      .catch(console.error);
  }, []);

  const columns = [
    { key: "dispute_id", label: "Dispute ID" },
    { key: "email_id", label: "Email ID" },
    { key: "invoice_id", label: "Invoice ID" },
    { key: "issue", label: "Issue" },
    { key: "priority", label: "Priority" },
    { key: "status", label: "Status" },
    { key: "created_at", label: "Created At" },
  ];

  return (
    <div className="page">
      <h1>Disputes</h1>
      <p>Dispute tickets generated by the AI agent.</p>

      <DataTable columns={columns} data={disputes} />
    </div>
  );
}

export default Disputes;