import { useEffect, useState } from "react";

import DataTable from "../components/DataTable";
import { getTasks } from "../services/api";

function Tasks() {
  const [tasks, setTasks] = useState([]);

  useEffect(() => {
    getTasks()
      .then((response) => setTasks(response.data))
      .catch(console.error);
  }, []);

  const columns = [
    { key: "task_id", label: "Task ID" },
    { key: "email_id", label: "Email ID" },
    { key: "invoice_id", label: "Invoice ID" },
    { key: "task_type", label: "Type" },
    { key: "priority", label: "Priority" },
    { key: "status", label: "Status" },
    { key: "created_at", label: "Created At" },
  ];

  return (
    <div className="page">
      <h1>Tasks</h1>
      <p>Payment follow-up tasks generated by the agent.</p>

      <DataTable columns={columns} data={tasks} />
    </div>
  );
}

export default Tasks;